export const FILE_TYPES = [
	// Image
	"image/*",
	"image/bmp.bmp",
	"image/gif.gif",
	"image/vnd.microsoft.icon.ico",
	"image/jpeg.jpeg",
	"image/jpeg.jpg",
	"image/png.png",
	"image/svg+xml.svg",
	"image/tiff.tif",
	"image/tiff.tiff",
	"image/webp.webp",

	// Video
	"video/*",
	"video/x-msvideo.avi",
	"video/mpeg.mpeg",
	"video/mp2t.ts",
	"video/ogg.ogv",
	"video/webm.webm",
	"video/3gpp.3gp",
	"video/3gpp2.3g2",
	"video/mp4.mp4",

	// Audio
	"audio/aac.aac",
	"audio/midi.mid",
	"audio/x-midi.midi",
	"audio/mpeg.mp3",
	"audio/ogg.oga",
	"audio/opus.opus",
	"audio/wav.wav",
	"audio/webm.weba",
	"audio/3gpp.3gp",
	"audio/3gpp2.3g2",

	// Text
	"text/*",
	"text/css.css",
	"text/csv.csv",
	"text/html.html",
	"text/html.htm",
	"text/javascript.js",
	"text/javascript.mjs",
	"text/plain.txt",
	"text/markdown.markdown",
	"text/markdown.md",
	"text/xml.xml",
	"text/calendar.ics",

	// Application
	"application/*",
	"application/x-abiword.abw",
	"application/x-freearc.arc",
	"application/vnd.amazon.ebook.azw",
	"application/octet-stream.bin",
	"application/x-bzip.bz",
	"application/x-bzip2.bz2",
	"application/x-csh.csh",
	"application/msword.doc",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document.docx",
	"application/vnd.ms-fontobject.eot",
	"application/epub+zip.epub",
	"application/gzip.gz",
	"application/java-archive.jar",
	"application/json.json",
	"application/ld+json.jsonld",
	"application/vnd.apple.installer+xml.mpkg",
	"application/vnd.oasis.opendocument.presentation.odp",
	"application/vnd.oasis.opendocument.spreadsheet.ods",
	"application/vnd.oasis.opendocument.text.odt",
	"application/ogg.ogx",
	"application/pdf.pdf",
	"application/php.php",
	"application/vnd.ms-powerpoint.ppt",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation.pptx",
	"application/vnd.rar.rar",
	"application/rtf.rtf",
	"application/x-sh.sh",
	"application/x-shockwave-flash.swf",
	"application/x-tar.tar",
	"application/vnd.visio.vsd",
	"application/xhtml+xml.xhtml",
	"application/vnd.ms-excel.xls",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.xlsx",
	"application/xml.xml",
	"application/vnd.mozilla.xul+xml.xul",
	"application/zip.zip",
	"application/x-7z-compressed.7z",

	// Font
	"font/*",
	"font/otf.otf",
	"font/ttf.ttf",
	"font/woff.woff",
	"font/woff2.woff2",
];
