import { ComplianceFlow } from "@/types/compliance.types";

export const COMPLIANCE_PREVIEW_DATA:ComplianceFlow = {
	id: "comp-flow-001",
	name: "Annual Business Compliance Assessment",
	description:
		"Comprehensive compliance assessment for business operations and regulatory requirements",
	status: "draft",
	sections: [
		{
			id: "section-001",
			flow_id: "comp-flow-001",
			title: "Employee Information & Background",
			description: "Employee personal information and background verification",
			modules: [
				{
					id: "module-001",
					section_id: "section-001",
					title: "Personal Information",
					description: "Basic employee personal details",
					field_rows: [
						{
							id: "field-row-001",
							form_block_id: null,
							super_block_module_id: null,
							module_id: "module-001",
							layout: "1-column",
							fields: [
								{
									id: "field-001",
									field_row_id: "field-row-001",
									type: "header",
									text: "Employee Personal Information",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-002",
									field_row_id: "field-row-001",
									type: "paragraph",
									text: "Please provide accurate personal information for compliance and verification purposes. All information will be kept confidential and used only for regulatory compliance.",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-003",
									field_row_id: "field-row-001",
									type: "info",
									content:
										"This section is required for all employees and contractors. Incomplete information may delay compliance processing.",
									info_type: "warning",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
						{
							id: "field-row-002",
							form_block_id: null,
							super_block_module_id: null,
							module_id: "module-001",
							layout: "2-column",
							fields: [
								{
									id: "field-004",
									field_row_id: "field-row-002",
									type: "text",
									label: "Full Legal Name",
									required: true,
									placeholder: "Enter your full legal name",
									description: "As it appears on government-issued ID",
									hint_text: "Include middle name if applicable",
									max_length: 100,
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-005",
									field_row_id: "field-row-002",
									type: "date",
									label: "Date of Birth",
									required: true,
									description: "For age verification and compliance",
									hint_text: "MM/DD/YYYY format",
									date_type: "date",
									date_format: "MM/DD/YYYY",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					form_blocks: [
						{
							id: "form-block-001",
							module_id: "module-001",
							title: "Contact Information",
							description: "Employee contact details and communication preferences",
							field_rows: [
								{
									id: "field-row-003",
									form_block_id: "form-block-001",
									super_block_module_id: null,
									module_id: null,
									layout: "2-column",
									fields: [
										{
											id: "field-006",
											field_row_id: "field-row-003",
											type: "email",
											label: "Work Email",
											required: true,
											placeholder: "employee@company.com",
											description: "Primary work email address",
											hint_text: "Use company email domain",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-007",
											field_row_id: "field-row-003",
											type: "tel",
											label: "Work Phone",
											required: true,
											placeholder: "(555) 123-4567",
											description: "Primary work phone number",
											hint_text: "Include extension if applicable",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-row-004",
									form_block_id: "form-block-001",
									super_block_module_id: null,
									module_id: null,
									layout: "1-column",
									fields: [
										{
											id: "field-008",
											field_row_id: "field-row-004",
											type: "url",
											label: "LinkedIn Profile",
											required: false,
											placeholder: "https://linkedin.com/in/yourprofile",
											description: "Professional networking profile",
											hint_text: "Optional but recommended for verification",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
						{
							id: "form-block-002",
							module_id: "module-001",
							title: "Employment Details",
							description: "Employment status and role information",
							field_rows: [
								{
									id: "field-row-005",
									form_block_id: "form-block-002",
									super_block_module_id: null,
									module_id: null,
									layout: "3-column",
									fields: [
										{
											id: "field-009",
											field_row_id: "field-row-005",
											type: "dropdown",
											label: "Employment Status",
											required: true,
											placeholder: "Select employment status",
											description: "Current employment classification",
											hint_text: "Choose the most appropriate status",
											multi_select: false,
											options: [
												{
													id: "opt-001",
													field_id: "field-009",
													label: "Full-time Employee",
													value: "full_time",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-002",
													field_id: "field-009",
													label: "Part-time Employee",
													value: "part_time",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-003",
													field_id: "field-009",
													label: "Contractor",
													value: "contractor",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-004",
													field_id: "field-009",
													label: "Intern",
													value: "intern",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-010",
											field_row_id: "field-row-005",
											type: "text",
											label: "Job Title",
											required: true,
											placeholder: "e.g., Senior Software Engineer",
											description: "Current job title and role",
											hint_text: "Use official job title from HR records",
											max_length: 100,
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-011",
											field_row_id: "field-row-005",
											type: "number",
											label: "Years of Experience",
											required: true,
											placeholder: "5",
											description: "Total years of professional experience",
											hint_text: "Include all relevant experience",
											min_value: 0,
											max_value: 50,
											step: 1,
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					super_blocks: [
						{
							id: "super-block-001",
							module_id: "module-001",
							title: "Background Verification",
							description: "Comprehensive background check and verification process",
							super_block_modules: [
								{
									id: "super-block-module-001",
									super_block_id: "super-block-001",
									title: "Criminal Background Check",
									max_entries: 5,
									min_entries: 1,
									summary_fields: [
										{
											id: "summary-field-001",
											field_row_id: "field-row-006",
											type: "text",
											label: "Case Number",
											required: true,
											placeholder: "Enter case number",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "summary-field-002",
											field_row_id: "field-row-006",
											type: "dropdown",
											label: "Status",
											required: true,
											placeholder: "Select status",
											multi_select: false,
											options: [
												{
													id: "opt-005",
													field_id: "summary-field-002",
													label: "Clear",
													value: "clear",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-006",
													field_id: "summary-field-002",
													label: "Pending",
													value: "pending",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-007",
													field_id: "summary-field-002",
													label: "Issues Found",
													value: "issues",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									field_rows: [
										{
											id: "field-row-006",
											form_block_id: null,
											super_block_module_id: "super-block-module-001",
											module_id: null,
											layout: "2-column",
											fields: [
												{
													id: "field-012",
													field_row_id: "field-row-006",
													type: "text",
													label: "Jurisdiction",
													required: true,
													placeholder: "e.g., California, Los Angeles County",
													description: "Legal jurisdiction for background check",
													hint_text: "Include state and county if applicable",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "field-013",
													field_row_id: "field-row-006",
													type: "date",
													label: "Check Date",
													required: true,
													description: "Date when background check was performed",
													hint_text: "Date of the actual check",
													date_type: "date",
													date_format: "MM/DD/YYYY",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-row-007",
											form_block_id: null,
											super_block_module_id: "super-block-module-001",
											module_id: null,
											layout: "1-column",
											fields: [
												{
													id: "field-014",
													field_row_id: "field-row-007",
													type: "file",
													label: "Background Check Report",
													required: true,
													placeholder: "Upload background check report",
													description: "Official background check documentation",
													hint_text: "PDF format preferred, max 10MB",
													file_types: ["pdf", "doc", "docx"],
													max_file_size: 10485760,
													multiple: false,
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "super-block-module-002",
									super_block_id: "super-block-001",
									title: "Reference Verification",
									max_entries: 3,
									min_entries: 2,
									summary_fields: [
										{
											id: "summary-field-003",
											field_row_id: "field-row-008",
											type: "text",
											label: "Reference Name",
											required: true,
											placeholder: "Enter reference name",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "summary-field-004",
											field_row_id: "field-row-008",
											type: "radio",
											label: "Verification Status",
											required: true,
											options: [
												{
													id: "opt-008",
													field_id: "summary-field-004",
													label: "Verified",
													value: "verified",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-009",
													field_id: "summary-field-004",
													label: "Pending",
													value: "pending",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-010",
													field_id: "summary-field-004",
													label: "Unreachable",
													value: "unreachable",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									field_rows: [
										{
											id: "field-row-008",
											form_block_id: null,
											super_block_module_id: "super-block-module-002",
											module_id: null,
											layout: "2-column",
											fields: [
												{
													id: "field-015",
													field_row_id: "field-row-008",
													type: "text",
													label: "Reference Name",
													required: true,
													placeholder: "Full name of reference",
													description: "Professional reference contact",
													hint_text: "Use full legal name",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "field-016",
													field_row_id: "field-row-008",
													type: "tel",
													label: "Reference Phone",
													required: true,
													placeholder: "(555) 123-4567",
													description: "Contact number for reference",
													hint_text: "Include country code if international",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-row-009",
											form_block_id: null,
											super_block_module_id: "super-block-module-002",
											module_id: null,
											layout: "1-column",
											fields: [
												{
													id: "field-017",
													field_row_id: "field-row-009",
													type: "checkbox",
													label: "Reference Verification Completed",
													required: true,
													description: "Confirmation of reference verification",
													hint_text: "Check when verification is complete",
													options: [
														{
															id: "opt-011",
															field_id: "field-017",
															label: "Reference contacted and verified",
															value: "contacted",
															created_at: "2024-01-15T10:00:00Z",
															updated_at: "2024-01-15T10:00:00Z",
														},
														{
															id: "opt-012",
															field_id: "field-017",
															label: "Professional relationship confirmed",
															value: "relationship_confirmed",
															created_at: "2024-01-15T10:00:00Z",
															updated_at: "2024-01-15T10:00:00Z",
														},
														{
															id: "opt-013",
															field_id: "field-017",
															label: "Performance evaluation received",
															value: "evaluation_received",
															created_at: "2024-01-15T10:00:00Z",
															updated_at: "2024-01-15T10:00:00Z",
														},
													],
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
						{
							id: "super-block-002",
							module_id: "module-001",
							title: "Education Verification",
							description: "Educational background and certification verification",
							super_block_modules: [
								{
									id: "super-block-module-003",
									super_block_id: "super-block-002",
									title: "Academic Credentials",
									max_entries: 3,
									min_entries: 1,
									summary_fields: [
										{
											id: "summary-field-005",
											field_row_id: "field-row-010",
											type: "text",
											label: "Institution Name",
											required: true,
											placeholder: "Enter institution name",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "summary-field-006",
											field_row_id: "field-row-010",
											type: "dropdown",
											label: "Degree Level",
											required: true,
											placeholder: "Select degree level",
											multi_select: false,
											options: [
												{
													id: "opt-014",
													field_id: "summary-field-006",
													label: "High School",
													value: "high_school",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-015",
													field_id: "summary-field-006",
													label: "Associate's",
													value: "associates",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-016",
													field_id: "summary-field-006",
													label: "Bachelor's",
													value: "bachelors",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-017",
													field_id: "summary-field-006",
													label: "Master's",
													value: "masters",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-018",
													field_id: "summary-field-006",
													label: "Doctorate",
													value: "doctorate",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									field_rows: [
										{
											id: "field-row-010",
											form_block_id: null,
											super_block_module_id: "super-block-module-003",
											module_id: null,
											layout: "2-column",
											fields: [
												{
													id: "field-018",
													field_row_id: "field-row-010",
													type: "text",
													label: "Institution Name",
													required: true,
													placeholder: "University of California",
													description: "Educational institution name",
													hint_text: "Use official institution name",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "field-019",
													field_row_id: "field-row-010",
													type: "text",
													label: "Degree/Certificate",
													required: true,
													placeholder: "Bachelor of Science in Computer Science",
													description: "Degree or certificate earned",
													hint_text: "Full degree title",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-row-011",
											form_block_id: null,
											super_block_module_id: "super-block-module-003",
											module_id: null,
											layout: "1-column",
											fields: [
												{
													id: "field-020",
													field_row_id: "field-row-011",
													type: "file",
													label: "Transcript or Certificate",
													required: true,
													placeholder: "Upload transcript or certificate",
													description: "Official academic documentation",
													hint_text: "PDF format, max 5MB",
													file_types: ["pdf", "jpg", "png"],
													max_file_size: 5242880,
													multiple: false,
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "super-block-module-004",
									super_block_id: "super-block-002",
									title: "Professional Certifications",
									max_entries: 5,
									min_entries: 0,
									summary_fields: [
										{
											id: "summary-field-007",
											field_row_id: "field-row-012",
											type: "text",
											label: "Certification Name",
											required: true,
											placeholder: "Enter certification name",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "summary-field-008",
											field_row_id: "field-row-012",
											type: "date",
											label: "Expiry Date",
											required: true,
											placeholder: "MM/DD/YYYY",
											date_type: "date",
											date_format: "MM/DD/YYYY",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									field_rows: [
										{
											id: "field-row-012",
											form_block_id: null,
											super_block_module_id: "super-block-module-004",
											module_id: null,
											layout: "3-column",
											fields: [
												{
													id: "field-021",
													field_row_id: "field-row-012",
													type: "text",
													label: "Certification Name",
													required: true,
													placeholder: "AWS Certified Solutions Architect",
													description: "Professional certification title",
													hint_text: "Use official certification name",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "field-022",
													field_row_id: "field-row-012",
													type: "text",
													label: "Issuing Organization",
													required: true,
													placeholder: "Amazon Web Services",
													description: "Organization that issued the certification",
													hint_text: "Official issuing body name",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "field-023",
													field_row_id: "field-row-012",
													type: "date",
													label: "Expiry Date",
													required: true,
													description: "Certification expiration date",
													hint_text: "When certification expires",
													date_type: "date",
													date_format: "MM/DD/YYYY",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					created_at: "2024-01-15T10:00:00Z",
					updated_at: "2024-01-15T10:00:00Z",
				},
				{
					id: "module-002",
					section_id: "section-001",
					title: "Compliance Declarations",
					description: "Employee compliance declarations and acknowledgments",
					field_rows: [
						{
							id: "field-row-013",
							form_block_id: null,
							super_block_module_id: null,
							module_id: "module-002",
							layout: "1-column",
							fields: [
								{
									id: "field-024",
									field_row_id: "field-row-013",
									type: "header",
									text: "Compliance Declarations",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-025",
									field_row_id: "field-row-013",
									type: "paragraph",
									text: "By completing this form, you acknowledge and agree to comply with all applicable laws, regulations, and company policies. You understand that providing false or misleading information may result in disciplinary action, including termination of employment.",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-026",
									field_row_id: "field-row-013",
									type: "info",
									content:
										"All information provided will be verified through appropriate channels. Please ensure accuracy and completeness of all responses.",
									info_type: "note",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					form_blocks: [],
					super_blocks: [],
					created_at: "2024-01-15T10:00:00Z",
					updated_at: "2024-01-15T10:00:00Z",
				},
			],
			created_at: "2024-01-15T10:00:00Z",
			updated_at: "2024-01-15T10:00:00Z",
		},
		{
			id: "section-002",
			flow_id: "comp-flow-001",
			title: "Financial Disclosure & Conflicts of Interest",
			description: "Financial interests and potential conflicts of interest disclosure",
			modules: [
				{
					id: "module-003",
					section_id: "section-002",
					title: "Financial Interests",
					description: "Disclosure of financial interests and investments",
					field_rows: [
						{
							id: "field-row-014",
							form_block_id: null,
							super_block_module_id: null,
							module_id: "module-003",
							layout: "1-column",
							fields: [
								{
									id: "field-027",
									field_row_id: "field-row-014",
									type: "header",
									text: "Financial Interest Disclosure",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-028",
									field_row_id: "field-row-014",
									type: "paragraph",
									text: "This section requires disclosure of all financial interests that may create or appear to create a conflict of interest with your employment responsibilities. This includes investments, business interests, and other financial relationships.",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-029",
									field_row_id: "field-row-014",
									type: "info",
									content:
										"Failure to disclose material financial interests may result in disciplinary action and potential legal consequences. When in doubt, disclose.",
									info_type: "warning",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					form_blocks: [
						{
							id: "form-block-003",
							module_id: "module-003",
							title: "Investment Holdings",
							description: "Disclosure of investment holdings and securities",
							field_rows: [
								{
									id: "field-row-015",
									form_block_id: "form-block-003",
									super_block_module_id: null,
									module_id: null,
									layout: "2-column",
									fields: [
										{
											id: "field-030",
											field_row_id: "field-row-015",
											type: "text",
											label: "Company/Entity Name",
											required: true,
											placeholder: "Apple Inc.",
											description: "Name of company or entity",
											hint_text: "Use official company name",
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
										{
											id: "field-031",
											field_row_id: "field-row-015",
											type: "number",
											label: "Value of Holdings",
											required: true,
											placeholder: "50000",
											description: "Current market value of holdings",
											hint_text: "Enter amount in USD",
											min_value: 0,
											max_value: 10000000,
											step: 1000,
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
						{
							id: "form-block-004",
							module_id: "module-003",
							title: "Business Relationships",
							description: "Disclosure of business relationships and affiliations",
							field_rows: [
								{
									id: "field-row-016",
									form_block_id: "form-block-004",
									super_block_module_id: null,
									module_id: null,
									layout: "1-column",
									fields: [
										{
											id: "field-032",
											field_row_id: "field-row-016",
											type: "radio",
											label: "Do you have any business relationships with competitors?",
											required: true,
											description: "Include consulting, advisory, or board positions",
											hint_text: "Select the most appropriate option",
											options: [
												{
													id: "opt-019",
													field_id: "field-032",
													label: "Yes",
													value: "yes",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-020",
													field_id: "field-032",
													label: "No",
													value: "no",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
												{
													id: "opt-021",
													field_id: "field-032",
													label: "Not Sure",
													value: "not_sure",
													created_at: "2024-01-15T10:00:00Z",
													updated_at: "2024-01-15T10:00:00Z",
												},
											],
											created_at: "2024-01-15T10:00:00Z",
											updated_at: "2024-01-15T10:00:00Z",
										},
									],
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
					super_blocks: [],
					created_at: "2024-01-15T10:00:00Z",
					updated_at: "2024-01-15T10:00:00Z",
				},
				{
					id: "module-004",
					section_id: "section-002",
					title: "Compliance Acknowledgments",
					description: "Acknowledgments and agreements to compliance policies",
					field_rows: [
						{
							id: "field-row-017",
							form_block_id: null,
							super_block_module_id: null,
							module_id: "module-004",
							layout: "1-column",
							fields: [
								{
									id: "field-033",
									field_row_id: "field-row-017",
									type: "header",
									text: "Compliance Policy Acknowledgments",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-034",
									field_row_id: "field-row-017",
									type: "paragraph",
									text: "By signing below, you acknowledge that you have read, understood, and agree to comply with all applicable compliance policies, including but not limited to the Code of Conduct, Anti-Corruption Policy, and Insider Trading Policy.",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
								{
									id: "field-035",
									field_row_id: "field-row-017",
									type: "info",
									content:
										"These acknowledgments are legally binding and may be used in compliance investigations or legal proceedings.",
									info_type: "note",
									created_at: "2024-01-15T10:00:00Z",
									updated_at: "2024-01-15T10:00:00Z",
								},
							],
							created_at: "2024-01-15T10:00:00Z",
							updated_at: "2024-01-15T10:00:00Z",
						},
					],
                    form_blocks: [],
                    super_blocks: [],
                    created_at: "2024-01-15T10:00:00Z",
                    updated_at: "2024-01-15T10:00:00Z",
				},
			],
			created_at: "2024-01-15T10:00:00Z",
			updated_at: "2024-01-15T10:00:00Z",
		},
	],
	created_at: "2024-01-15T10:00:00Z",
	updated_at: "2024-01-15T10:00:00Z",
};
